# Use a base image that includes bash and other useful utilities.
# The debian:buster-slim image is a good choice for this.
FROM debian:buster-slim

# Copy the script into the container.
COPY create-jwtsecret.sh /usr/local/bin/create-jwtsecret.sh

# Install openssl.
RUN apt-get update && \
    apt-get install -y openssl && \
    chmod +x /usr/local/bin/create-jwtsecret.sh && \
    mkdir -p /secrets

# Set the entrypoint to run your script.
ENTRYPOINT ["/usr/local/bin/create-jwtsecret.sh"]
