version: "3.8"

services:
  execution:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.erigon
    stop_grace_period: 5m
    image: erigon:local
    user: erigon
    volumes:
      - erigon_data:/var/lib/erigon
      - jwtsecret:/var/lib/erigon/jwtsecret
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 30304:30304/tcp
      - 30304:30304/udp
      - 30305:30305/tcp
      - 30305:30305/udp
      - 42069:42069/tcp
      - 42069:42069/udp
    networks:
      default:
        aliases:
          - eth1

  consensus:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.lighthouseconsensus
    image: lighthouse:local
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - beacon-data:/var/lib/lighthouse
      - jwtsecret:/var/lib/lighthouse/beacon/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9001:9001/udp
    networks:
      default:
        aliases:
          - eth2


volumes:
  beacon-data:
  execution-data:
  jwtsecret:
