version: "3.8"

services:
  jwtsecret-generator:
    image: alpine
    container_name: jwtsecret-generator-container
    volumes:
      - jwtsecret-volume:/secrets
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Creating JWT secret..."
        apk --no-cache add openssl;
        openssl rand -hex 32 | tr -d "\n" > /secrets/jwtsecret.hex
        chmod 644 /secrets/jwtsecret.hex
    restart: on-failure

  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    container_name: erigon-container
    volumes:
      - erigon-data:/var/lib/erigon
      - jwtsecret-volume:/secrets
    ports:
      - "8551:8551"
      - "8545:8545"
      - "30303:30303"
      - "30304:30304"
      - "9090:9090"
    expose:
      - 8551
    networks:
      - eth2

  lighthouse-beacon:
    build:
      context: .
      dockerfile: Dockerfile.lighthousebeacon
    container_name: lighthouse-beacon-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
      - jwtsecret-volume:/secrets
    ports:
      - 9000:9000
      - 9000:9000/udp
      - 5052:5052
      - 5053:5053
    expose:
      - 5052
    networks:
      - eth2

  lighthouse-validator:
    build:
      context: .
      dockerfile: Dockerfile.lighthousevalidator
    container_name: lighthouse-validator-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
    networks:
      - eth2

volumes:
  erigon-data:
  lighthouse-data:
  jwtsecret-volume:

networks:
  eth2:
