version: "3.8"

x-common-logging: &common-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "5"

services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./execution
    stop_grace_period: 5m
    image: erigon
    container_name: execution-container
    user: erigon
    volumes:
      - erigon-data:/var/lib/erigon
      - jwtsecret:/var/lib/erigon/jwtsecret
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 30304:30304/tcp
      - 30304:30304/udp
      - 30302:30302/tcp
      - 30302:30302/udp
      - 42069:42069/tcp
      - 42069:42069/udp
      - 8545:8545/tcp
    networks:
      default:
        aliases:
          - eth1
    environment:
      - ETH_NETWORK=${ETH_NETWORK}
      - LOG_LEVEL=${LOG_LEVEL}
    logging: *common-logging

  consensus:
    restart: "unless-stopped"
    build:
      context: ./consensus
    image: lighthouse-consensus
    container_name: consensus-container
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lighthouse-beacon-data:/var/lib/lighthouse
      - jwtsecret:/var/lib/lighthouse/beacon/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9005:9005/udp
    expose:
      - "5052"
    networks:
      default:
        aliases:
          - eth2
    environment:
      - ETH_NETWORK=${ETH_NETWORK}
      - FEE_RECIPIENT=${FEE_RECIPIENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - MEVBOOST_RELAYS=${MEVBOOST_RELAYS}
    logging: *common-logging

  validator:
    restart: "unless-stopped"
    build:
      context: ./validator
    image: lighthouse-validator
    container_name: validator-container
    user: lhvalidator
    volumes:
      - ./.eth/ethereum-keys:/keystore
      - lighthouse-validator-data:/var/lib/lighthouse
    depends_on:
      - consensus
    networks:
      default:
        aliases:
          - validator
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ETH_NETWORK=${ETH_NETWORK}
      - FEE_RECIPIENT=${FEE_RECIPIENT}
      - LOG_LEVEL=${LOG_LEVEL}
      - MEVBOOST_RELAYS=${MEVBOOST_RELAYS}
    logging: *common-logging

  metrics-exporter:
    image: samcm/ethereum-metrics-exporter:0.21.0-debian
    restart: "unless-stopped"
    entrypoint:
      - "/ethereum-metrics-exporter"
      - "--consensus-url=http://consensus:5052"
      - "--execution-url=http://execution:8545"
    networks:
      default:
        aliases:
          - metrics-exporter
    logging: *common-logging

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/$$(dev|proc|sys|run|var/lib/docker/.+)($$|/)"
      - "--no-collector.ipvs"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/localtime:/etc/localtime:ro
    logging: *common-logging

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:master
    volumes:
      - ./configs/blackbox.yml:/config/blackbox.yml
    command:
      - --config.file=/config/blackbox.yml
    logging: *common-logging

  json-exporter:
    restart: "unless-stopped"
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./configs/json.yml:/config/json.yml
    command:
      - --config.file
      - /config/json.yml
    logging: *common-logging

  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: grafana
    environment:
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
    entrypoint: ["provision-dashboards.sh"]
    ports:
      - "3000:3000"
    command: /run.sh
    logging: *common-logging

  prometheus:
    restart: "unless-stopped"
    build:
      context: ./prometheus
    image: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom-data:/prometheus
    logging: *common-logging

  mev-boost:
    restart: "unless-stopped"
    image: flashbots/mev-boost:latest
    container_name: mevboost-container
    ports:
      - 18550:18550
    networks:
      default:
        aliases:
          - mevboost
    environment:
      - MEVBOOST_RELAYS=${MEVBOOST_RELAYS}
      - ETH_NETWORK=${ETH_NETWORK}
    command: >
      -${ETH_NETWORK}
      -addr 0.0.0.0:18550
      -relay-check
      -relay ${FLASH_BOTS_RELAY}
      -relay ${BLOXROUTE_MAX_PROFIT_RELAY}
      -relay ${ULTRA_SOUND_RELAY}
      -relay ${AGNOSTIC_BOOST_RELAY}
      -relay ${AESTUS_RELAY}
      -relay ${MANIFOLD_RELAY}
      -relay ${EDEN_NETWORK_RELAY}
    logging: *common-logging

volumes:
  lighthouse-beacon-data:
  lighthouse-validator-data:
  erigon-data:
  jwtsecret:
  grafana-data:
  grafana-config:
  prom-data:

