# Beacon Dockerfile
FROM lighthouse-base

# Entry point for running Lighthouse Beacon Node
ENTRYPOINT ["/usr/local/bin/lighthouse", "bn", \
    "--network", "goerli", \
    "--datadir", "/var/lib/lighthouse", \
    "--http", \
    "--execution-endpoint", "http://erigon:8551", \
    "--execution-jwt", "/secrets/jwtsecret", \
    "--checkpoint-sync-url", "https://prater.checkpoint.sigp.io", \
    "--metrics"]