version: "3.8"

services:
  execution:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.erigon
    stop_grace_period: 1m
    image: erigon
    container_name: execution-container
    user: erigon
    volumes:
      - erigon-data:/var/lib/erigon
      - jwtsecret:/var/lib/erigon/jwtsecret
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 30304:30304/tcp
      - 30304:30304/udp
      - 30305:30305/tcp
      - 30305:30305/udp
      - 42069:42069/tcp
      - 42069:42069/udp
    networks:
      default:
        aliases:
          - eth1
    environment:
      - ETH_NETWORK=${ETH_NETWORK}

  consensus:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.lighthouseconsensus
    image: lighthouse-consensus
    container_name: consensus-container
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lighthouse-beacon-data:/var/lib/lighthouse
      - jwtsecret:/var/lib/lighthouse/beacon/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9001:9001/udp
    networks:
      default:
        aliases:
          - eth2
    environment:
      - ETH_NETWORK=${ETH_NETWORK}

  validator:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.lighthousevalidator
    image: lighthouse-validator
    container_name: validator-container
    user: lhvalidator
    volumes:
      - lighthouse-validator-data:/var/lib/lighthouse
    entrypoint:
      # - /keymanager.sh
      - lighthouse
      - vc 
      - --network
      - $ETH_NETWORK
      - --datadir
      - /var/lib/lighthouse 
      - --beacon-nodes
      - http://consensus:5052 
      - --metrics 
      - --metrics-address
      - "0.0.0.0"
      - --metrics-port
      - "8009"
      - --http 
      - --http-port
      - "7500"
      - --http-address
      - "0.0.0.0"
      - --http-allow-origin=* 
      - --unencrypted-http-transport 
      - --suggested-fee-recipient
      - "0xe81a5054567C95db393751AC6194F925eDb8B3c0"
    depends_on:
      - consensus
    networks:
      default:
        aliases:
          - validator
    environment:
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ETH_NETWORK=${ETH_NETWORK}

  metrics-exporter:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.metrics-exporter

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points='^/(dev|proc|sys|run|var/lib/docker/.+)($|/)'"
      - "--no-collector.ipvs"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/localtime:/etc/localtime:ro

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:master
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - --config.file=/config/blackbox.yml

  json-exporter:
    restart: "unless-stopped"
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./json.yml:/config/json.yml
    command:
      - --config.file
      - /config/json.yml

  cryptowat-exporter:
    restart: "unless-stopped"
    image: nbarrientos/cryptowat_exporter:latest
    environment:
      - CRYPTOWAT_EXCHANGES=kraken
      - CRYPTOWAT_PAIRS=etheur,ethusd,ethgbp,ethcad,ethchf,ethjpy,ethbtc
      - CRYPTOWAT_CACHESECONDS=300
      - TZ=Europe/Zurich

volumes:
  lighthouse-beacon-data:
  lighthouse-validator-data:
  erigon-data:
  jwtsecret:
