version: "3.8"

services:
  jwtsecret-creator:
    build:
      context: .
      dockerfile: Dockerfile.jwtsecret
    container_name: jwtsecret-creator-container
    volumes:
      - jwtsecret-volume:/secrets
    restart: "no"

  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    container_name: erigon-container
    volumes:
      - jwtsecret-volume:/secrets
      - erigon-data:/var/lib/erigon
    ports:
      - "8545:8545"
    depends_on:
      - jwtsecret-creator
    healthcheck:
      test: ["CMD-SHELL", "[ -f /secrets/jwtsecret ]"]
      interval: 5s
      timeout: 10s
      retries: 5

  lighthouse:
    build:
      context: .
      dockerfile: Dockerfile.lighthouse
    container_name: lighthouse-container
    volumes:
      - jwtsecret-volume:/secrets
      - lighthouse-data:/var/lib/lighthouse
    depends_on:
      - jwtsecret-creator
      - erigon
    healthcheck:
      test: ["CMD-SHELL", "[ -f /secrets/jwtsecret ]"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  jwtsecret-volume:
  erigon-data:
  lighthouse-data:
