# Use the specified base image
FROM sigp/lighthouse

# Set the working directory
WORKDIR /var/lib/lighthouse

# Command to run the Lighthouse consensus client
CMD ["lighthouse", "bn", "--network", "goerli", "--datadir", "/var/lib/lighthouse", "--http", "--execution-endpoint", "http://erigon:8551", "--checkpoint-sync-url", "https://prater.checkpoint.sigp.io", "--metrics"]
