version: "3.8"

services:
  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    container_name: erigon-container
    volumes:
      - erigon-data:/var/lib/erigon
      - jwtsecret-volume:/secrets
    ports:
      - "8551:8551"
      - "8545:8545"

  lighthouse-base:
    build:
      context: .
      dockerfile: Dockerfile.lighthousebase
    image: lighthouse-base

  lighthouse-beacon:
    build:
      context: .
      dockerfile: Dockerfile.beacon
    image: lighthouse-beacon
    container_name: lighthouse-beacon-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
      - jwtsecret-volume:/secrets
    depends_on:
      - erigon

  lighthouse-validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
    image: lighthouse-validator
    container_name: lighthouse-validator-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
      - jwtsecret-volume:/secrets
    depends_on:
      - erigon

  jwtsecret-generator:
    image: alpine
    container_name: jwtsecret-generator-container
    volumes:
      - jwtsecret-volume:/secrets
    entrypoint:
      - /bin/sh
      - -c
      - |
        if [ ! -f /secrets/jwtsecret ]; then
          apk --no-cache add openssl;
          openssl rand -hex 32 | tr -d "\n" > /secrets/jwtsecret;
        fi
    restart: on-failure

volumes:
  erigon-data:
  lighthouse-data:
  jwtsecret-volume:
