version: "3.8"

services:
  execution:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.erigon
    stop_grace_period: 5m
    image: erigon
    user: erigon
    volumes:
      - erigon-data:/var/lib/erigon
      - jwtsecret:/var/lib/erigon/jwtsecret
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 30304:30304/tcp
      - 30304:30304/udp
      - 30305:30305/tcp
      - 30305:30305/udp
      - 42069:42069/tcp
      - 42069:42069/udp
    networks:
      default:
        aliases:
          - eth1

  consensus:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.lighthouseconsensus
    image: lighthouse-consensus
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lighthouse-beacon-data:/var/lib/lighthouse
      - jwtsecret:/var/lib/lighthouse/beacon/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 9001:9001/udp
    networks:
      default:
        aliases:
          - eth2

  validator:
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile.lighthousevalidator
    image: lighthouse-validator
    user: lhvalidator
    volumes:
      - lighthouse-validator-data:/var/lib/lighthouse
    depends_on:
      - consensus
    networks:
      default:
        aliases:
          - validator



volumes:
  lighthouse-beacon-data:
  lighthouse-validator-data:
  erigon-data:
  jwtsecret:
