version: "3.8"

services:
  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    container_name: erigon-container
    volumes:
      - erigon-data:/var/lib/erigon
    ports:
      - "8545:8545"

  lighthouse:
    build:
      context: .
      dockerfile: Dockerfile.lighthouse
    container_name: lighthouse-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
    depends_on:
      - erigon

volumes:
  erigon-data:
  lighthouse-data:
