version: "3.8"

services:
  erigon:
    build:
      context: .
      dockerfile: Dockerfile.erigon
    container_name: erigon-container
    volumes:
      - erigon-data:/var/lib/erigon
      # - jwtsecret-volume:/secrets
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30304:30304"
      - "9090:9090"
    expose:
      - 8551
    networks:
      - eth2

  lighthouse-beacon:
    build:
      context: .
      dockerfile: Dockerfile.lighthousebeacon
    container_name: lighthouse-beacon-container
    volumes:
      - lighthouse-data:/var/lib/lighthouse
      # - jwtsecret-volume:/secrets
    ports:
      - 9000:9000
      - 9000:9000/udp
      - 5052:5052
      - 5053:5053
    networks:
      - eth2

  # jwtsecret-generator:
  #   image: alpine
  #   container_name: jwtsecret-generator-container
  #   volumes:
  #     - jwtsecret-volume:/secrets
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       if [ ! -f /secrets/jwtsecret.hex ]; then
  #         echo "Creating JWT secret..."
  #         apk --no-cache add openssl;
  #         openssl rand -hex 32 | tr -d "\n" | sudo tee jwtsecret.hex
  #       fi
  #   restart: on-failure

volumes:
  erigon-data:
  lighthouse-data:
  # jwtsecret-volume:

networks:
  eth2:
