{
 "title": "Vitals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Resident Memory Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum(node_filesystem_free_bytes) / sum(node_filesystem_size_bytes))) * 100\n",
     "legendFormat": "% Used"
    },
    { "expr": "db_size", "legendFormat": "Node Size" }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(eth_exe_gas_price_gwei[1h])/10e7",
     "legendFormat": "Price"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "rate(p2p_ingress[5m])\n", "legendFormat": "Inbound" },
    { "expr": "rate(p2p_egress[5m])", "legendFormat": "Outbound" }
   ]
  },
  {
   "title": "Connected Beacon Clients",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers_per_client", "legendFormat": "{{Client}}" }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "Execution (Erigon)" },
    { "expr": "libp2p_peers", "legendFormat": "Beacon (Lighthouse)" }
   ]
  },
  {
   "title": "Sync stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sync", "legendFormat": "{{stage}}" }
   ]
  },
  {
   "title": "Tree Hash Times [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_processing_block_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_block_root_seconds_count[5m])",
     "legendFormat": "Block Tree"
    },
    {
     "expr": "rate(beacon_block_processing_state_root_seconds_sum[5m])\n/\nrate(beacon_block_processing_state_root_seconds_count[5m])",
     "legendFormat": "State Tree"
    }
   ]
  },
  {
   "title": "Observed Validators",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_attn_observation_epoch_attesters",
     "legendFormat": "Attesters"
    },
    {
     "expr": "beacon_attn_observation_epoch_aggregators",
     "legendFormat": "Aggregators"
    },
    {
     "expr": "beacon_current_active_validators",
     "legendFormat": "Active"
    },
    {
     "expr": "beacon_head_state_active_validators_total",
     "legendFormat": "Total"
    },
    {
     "expr": "beacon_head_state_slashed_validators_total",
     "legendFormat": "Slashed"
    },
    {
     "expr": "beacon_head_state_withdrawn_validators_total",
     "legendFormat": "Withdrawable"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "Pending" },
    { "expr": "txpool_queued", "legendFormat": "Queued" },
    { "expr": "txpool_basefee", "legendFormat": "Basefee" }
   ]
  },
  {
   "title": "Validators ETH Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_head_state_validator_balances_total/10e8",
     "legendFormat": "Balance"
    },
    {
     "expr": "beacon_current_active_validators",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}